language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: '7.4snapshot'
  fast_finish: true

before_install:
  - composer config --auth http-basic.repo.packagist.com token $PACKAGIST_TOKEN
before_script:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit
after_script:
  - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

cache:
  directories:
    - $HOME/.composer/cache/files
