version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      #- ${BASE_DIR}/wordpress-site:/var/www/html
      - wordpress:/var/www/html
      - ${BASE_DIR}:/var/www/html/wp-content/plugins/multilingualpress-2-to-3-migration
      - ${BASE_DIR}/wordpress-site/wp-content/plugins/multilingualpress:/var/www/html/wp-content/plugins/multilingualpress
      - ${BASE_DIR}/wordpress-site/wp-content/plugins/multilingual-press:/var/www/html/wp-content/plugins/multilingual-press
    depends_on:
      - mysql
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ${BASE_DIR}/mysql-data:/var/lib/mysql
    ports:
      - 8082:3306
  phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 1234:80
  test:
    build:
      dockerfile: "Dockerfile_test"
      context: ./docker/
    volumes:
      - ${BASE_DIR}:/opt/project
    depends_on:
      - wordpress
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
  cli:
    image: wordpress:cli
    volumes:
      #- ${BASE_DIR}/wordpress-site:/var/www/html
      - wordpress:/var/www/html
      - ${BASE_DIR}:/var/www/html/wp-content/plugins/multilingualpress-2-to-3-migration
volumes:
  wordpress:
